### ISSUE TITLE
Implement real-time painting display for guessing players. They cannot make changes to the whiteboard or enter answers during drawing phase.

### ISSUE THREAD

**Issue by runzeliuzh** [sopra-fs23-group-19/sopra-fs23-group-19-client#56]

**Comment by GY-Meng** [comment]
the whiteboard connected with timer 8a7c5bcf84d9f728cc43ecdca82efb2e64cd6c3a

**Comment by GY-Meng** [comment]
the whiteboard cannot be used by the guessing player 17dc75db7119f0f27efa9f50a9ef7e2ec646392a

**Comment by runzeliuzh** [comment]
5d4ecb2

**Comment by runzeliuzh** [comment]
Instant painting sharing function complete. 5d4ecb2
